### ISSUE TITLE
Nie dziala majkraft!!!!

### ISSUE THREAD

**Issue by trazoid** [Witut2005/xaninOS#5]
czemnu nie maozna odpalic majnkrafta guwno system!!!!!!!!!!!!!!!!!!!! daje 1 gwiazdke bo nie moge 0!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! nei pobieracc!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! jak zxrobisz minekrafdt to dam 5 gwiazdek

**Comment by Witut2005** [comment]
huj

**Comment by trazoid** [comment]
1. baziew
2. syf
3. wylewa ci sie sraka z cottonworldow

**Comment by Witut2005** [comment]
1000101

**Comment by trazoid** [comment]
192.168.0.2

**Comment by trazoid** [comment]
h
